Repository atiladefreitas/dooing, pull requests merged in 2024-11, with the labels that each got.

#9 Adding search functionality
  lua/dooing/config.lua
  lua/dooing/state.lua
  lua/dooing/ui.lua
Labels: enhancement, backlog

#10 Improve help window toggle functionality
  lua/dooing/ui.lua
Labels: enhancement

#13 Enhanced task prioritization
  README.md
  lua/dooing/config.lua
  lua/dooing/init.lua
  lua/dooing/state.lua
  lua/dooing/ui.lua
Labels: documentation, enhancement, feature request, backlog
